# Generated by Django 3.2.9 on 2021-11-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20211113_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='note',
        ),
        migrations.AddField(
            model_name='category',
            name='note',
            field=models.ManyToManyField(to='todo.Note'),
        ),
    ]
