# Generated by Django 3.2.9 on 2021-11-16 00:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0008_auto_20211116_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='guests',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
