# Generated by Django 3.2.9 on 2021-11-20 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_board_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='todo.column'),
        ),
    ]
