# Generated by Django 4.0 on 2021-12-17 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0011_note_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='guests',
            field=models.ManyToManyField(related_name='guested_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
